### ISSUE TITLE
feat(mixin): Support configuration mixin.

### ISSUE THREAD

**Issue by CarmJos** [CarmJos/EasyUpdater#1]
支持 `yaml` `properties` `json` 等基础配置类型的解析与替换。

### 实际使用

首先，我们需要准备需要替换进实例配置文件的内容
`<path-to-configs>/survival-server.properties`
```properties
gamemode=survival
motd=
difficulty=hard
network-compression-threshold=-1
max-players=200
spawn-protection=0
```

随后，在实例的配置文件中，我们需要设定源文件和目标文件

```yaml
mixin:
  "server":
      source: "<path-to-configs>/survival-server.properties"
      target: "server.propertis"
```

在服务器启动后，会预先读取 源文件 内的配置条目，然后写入到服务器根目录下的 `server.propertis` 中。

### 额外注明

在 Mixin 写入的过程中，需要按照配置条目的顺序注入，以支持 “先注入总配置，再注入特定配置” 的功能。
