### ISSUE TITLE
feat(conf): Project configuration file examples and explanations.

### ISSUE THREAD

**Issue by CarmJos** [CarmJos/EasyUpdater#2]
```yaml
debug: false

import: # import configs, support wildcards
  - "xxxx/*.yaml" 

transfer:
  example-file:
    source: "<path-to-plugin-source>/ExamplePlugin-(.*)-SNAPSHOT.jar"
    target: "plugins/ExamplePlugin(.*).jar" # Target file
    options:
      rename: "ExamplePlugin-$1.jar"

  example-folder:
    source: "<path-to-plugin-source>/some-files/"
    target: "goods" # Target folder
    options:
      mode: "OVERRIDE"
      filter:
        - "*.log"
        - "*.log.gz"
 

mixin:
  example:
    schme: YAML # Optional, auto detect by file suffix.
    source: "<path-to-source>/xxx.yaml"
    target: "plugins/some-plugin/config.yml"
      
```

- [X] `import` 导入更多配置
- [x] `transfer` 更新内容 #5 
- [x] `mixin` 注入内容 #1
