### ISSUE TITLE
feat(transfer): Support file transfer & update.

### ISSUE THREAD

**Issue by CarmJos** [CarmJos/EasyUpdater#5]
文件替换可配置来源路径(source)和目标路径(target)，均支持模式匹配。

```yaml
transfer:
  example-file:
    source: "<path-to-sources>/ExamplePlugin/(.*)/ExamplePlugin-(.*)-SNAPSHOT.jar"
    target: "plugins/ExamplePlugin(.*).jar" # Target file
    options:
      rename: "ExamplePlugin-$2.jar"

  example-folder:
    source: "<path-to-plugin-source>/some-files/"
    target: "goods" # Target folder
    options:
      exists: "OVERRIDE"
      filter:
        - "*.log"
        - "*.log.gz"
```

需要注意判断来源和目标到底是文件还是文件夹；特别是在来源是文件，目标是文件夹的时候还需要做额外处理。

### 文件处理

在进行文件更新时，若有多个匹配的来源文件，则取首个匹配的文件。若有多个匹配的目标文件，则先全部移除。如果没有任何匹配的目标文件，则直接进行接下来的操作即可。

随后，若有配置重命名选项，则进行重命名，重命名支持模式匹配和模式变量(`$?`，对应来源路径中的模式变量)。

需要注意的是，路径有时候也会存在变量，如 `/var/repo/plugins/latests/game-(\\d+)/ExampleGame-(.*)-SNAPSHOT.jar`。可以在处理试以路径分隔符分割，然后逐一处理获得目标文件。

以 `example-file` 配置为例，将会找到 `<path-to-sources>/ExamplePlugin/1.0.1-SNAPSHOT/ExamplePlugin-1.0.1-SNAPSHOT.jar` 并以 `ExamplePlugin-1.0.1.jar` 的文件名，替换掉 `plugins/ExamplePlugin-1.0.0.jar` 。

### 文件夹处理

在进行文件夹更新时，需要额外判断是否有不要的文件。

当目标文件夹已经存在了同样文件时，支持以下处理方式：
- OVERRIDE 若存在，则覆盖
- SKIP 跳过
